### ISSUE TITLE
Sticky audio player

### ISSUE THREAD

**Issue by gusaus** [OpenProducer/openproducer-platform#16]
We need an audio player with the following features/functionality - 

- Customizable
- Live Streaming
- Analytics and Reporting

**Comment by gusaus** [comment]
Newspack plugin provides the following blocks and embeds - 
![Edit Post ‹ Newspack — WordPress - Mozilla Firefox 2020-02-25 16-50-52](https://user-images.githubusercontent.com/113996/75301196-fc99eb00-57ee-11ea-81f8-550f0dd8be0d.png)

**Comment by gusaus** [comment]
Keeping this issue open until we're able to include some sort of sticky audio player in our MVP.

Couple options we're looking at - 
- Newspack is looking to include at some point https://github.com/orgs/Automattic/projects/85#card-23754240
- Discussing various options in the LibreTime forum - https://discourse.libretime.org/t/custom-audio-players/140

**Comment by gusaus** [comment]
As we're now including Radio Station plugin in the MVP https://github.com/OpenProducer/openproducer-platform/issues/2#issuecomment-615429938, it would be great to include the streaming player in the works 

Problem there is we would like to include a player that is freely available. Obviously we don't want to interfere with @tonyzeoli's model to sustain, but at the same time there are multiple projects we could already include or build upon https://github.com/netmix/radio-station-pro/issues/33. 

With projects we're already including or planning to integrate (LibreTime, AzuraCast, and Newspack) already providing or having a similar need, I'm wondering if there are ways to could pool resources (dev and funds) for a freely available solution we could include.

**Comment by tonyzeoli** [comment]
In Radio Station, we will have a free player, but it will be a sidebar
widget (or block) and not a sticky footer player, which will be in PRO.


[image: photo]
Tony Zeoli
Founder, Digital Strategy Works LLC
O  (828) 412-0990  <(828) 412-0990> M  (917) 705-4700  <(917)
705-4700> E  az@digitalstrategyworks.com
<az@digitalstrategyworks.com>
W  https://digitalstrategyworks.com
Whatsapp 9177054700
Skype tonyzeoli
<http://www.facebook.com/digitalstrategyworks>
<http://www.twitter.com/dswks>
<http://www.linkedin.com/company/digital-strategy-works>
<http://plus.google.com/digitalstrategyworks>
<http://slideshare.com/tonyzeoli> <http://about.me/tonyzeoli>
<http://angel.co/tonyzeoli>
<https://calendly.com/tonyzeoli> Schedule a 30-minute Meeting
<https://digitalstrategyworks.com/clearly-better-days-cbd-oil-ecommerce-site-enhancements/2019/10/07/2841/?utm_source=rss&utm_medium=rss&utm_campaign=clearly-better-days-cbd-oil-ecommerce-site-enhancements>
Latest
post: Clearly Better Days CBD Oil Ecommerce Site Enhancements
<https://digitalstrategyworks.com/clearly-better-days-cbd-oil-ecommerce-site-enhancements/2019/10/07/2841/?utm_source=rss&utm_medium=rss&utm_campaign=clearly-better-days-cbd-oil-ecommerce-site-enhancements>


<https://gsuite.google.com/landing/partners/referral/trial.html?utm_source=sign-up&utm_medium=referralbutton1&utm_campaign=apps-referral-program&utm_content=https://goo.gl/BG4yH8>
<https://facebook.com/digitalstrategyworks>   <http://dswks>
<https://linkedin.com/in/+tonyzeoli>
<https://www.youtube.com/+digitalstrategyworks>

**Comment by tonyzeoli** [comment]
P.S. The free player will probably come within the month, if all goes
according to plan.

**Comment by gusaus** [comment]
> In Radio Station, we will have a free player, but it will be a sidebar widget (or block) and not a sticky footer player, which will be in PRO.

I'd like to include the free player in the MVP and then direct resources towards making improvements with a paid beta https://github.com/OpenProducer/openproducer-platform/issues/11

Ideally with the same devs making the Radio Station player leading the effort.

**Comment by gusaus** [comment]
We're having a parallel discussion on sticky player options in the LibreTime forum - 
https://discourse.libretime.org/t/custom-audio-players/140/22?u=gusaus

I'd like to see if we can work towards a solution we can share between projects and direct resources towards making that happen.

**Comment by gusaus** [comment]
Copying over some related discussion from the LibreTime forums - 

from @Robbt with regards to my question about if this should be stand-alone project https://discourse.libretime.org/t/custom-audio-players/140/25
> I think that Radio station plugin is a separate project in and of itself but the web player plugin they are developing should be stand-alone and at the same time compatible with LibreTime and other radio streams.

from @majick777 https://discourse.libretime.org/t/custom-audio-players/140/29
> I am playing with some code to try to use a common HTML element structure and styles for the player, but with the option of using one of a number of different javascript libraries for the player script. (Amplitude, Jplayer, Howler, Media Elements.) I’m doing the coding in a WordPress context but depending on what I end up it may be useable or modifyable for other platforms.
> 
> As for the continuous playback, yes that is a potential solution I am keen to pursue. The History API transition loading would be a cool WordPress plugin in it’s own right, as not having to convert your WordPress site to a headless javascript loading one just to make that happen is a real plus.
> 
> But I haven’t yet tried combining those with a Sticky Element. There is an additional challenge… Since with this method the current player could be “within” each of the loaded pages, there needs to be some additional code to communicate between player instances so that the any newly displayed player controls would be able to pause the existing player audio.
> 
> Further from this would be later solving the problem of possibly having multiple tabs playing audio from a site… There are websockets and things to communicate between windows and stop a stream in another player so this shouldn’t be too hard either, but that gives you an idea of what needs to be solved over time.

Me https://discourse.libretime.org/t/custom-audio-players/140/30
> Most of this is over my head (even with coffee) but my takeaway is there’s some overlap with what’s on the Radio Station/WordPress roadmap and needs of both LibreTime and AzuraCast.

> Would it be possible to scope out x-project solution?

from @majick777 https://discourse.libretime.org/t/custom-audio-players/140/31
> As I go I’m trying to write it in a way that works both within WordPress and without it, but this means adding a bunch of extra functions and function checks just to replicate some of what WordPress does already. Am making good headway though.

...and some related discussion in https://github.com/OpenProducer/openproducer-platform/issues/18#issuecomment-632457019 https://github.com/OpenProducer/openproducer-platform/issues/18#issuecomment-634344166 https://github.com/OpenProducer/openproducer-platform/issues/18#issuecomment-634409491

Based on these discussions it seems like @majick777 & @tonyzeoli are making progress on player(s) that will be included in the Radio Station plugin https://github.com/netmix/radio-station. 

As noted in https://github.com/OpenProducer/openproducer-platform/issues/18#issuecomment-634512087

> What if we identified a common set of features and developed the player as a separate project - which could then be modified and included with LibreTime, AzuraCast, and even Radio Station PRO.

> Instead of having one company responsible for developing and maintaining, we could pool resources (contributors, funds, and open-source code).

Could the same team working on the Radio Station player(s) properly scope this out (including budget requirements) take the lead on this?

Assuming all the projects involved are on Open Collective, there's a good bit of flexibility in terms of how to channel funds from users/supports to contributors.

**Comment by gusaus** [comment]
This player https://pro.radio/theme-features/radio-player/, part of the WordPress Pro.Radio & OnAir2 themes, integrates with AirTime/LibreTime provides good inspiration for a stand-alone player.

**Comment by gusaus** [comment]
With complimentary projects (and funders) participating, [FundOSS](https://fundoss.org/) could provide an opportunity for anyone interested to develop/release a stand-alone player.

**Comment by gusaus** [comment]
Closing this down as we can use the player included with Radio Station plugin. https://github.com/OpenProducer/openproducer-platform/issues/9
